
name: Rollback AWS CI/CD Demo

on:
  workflow_dispatch:
    inputs:
      release_sha:
        description: "Git commit SHA to rollback to"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  S3_BUCKET: aws-cicd-demo-bcc33d56677b9a2cb6bdb0ba40
  AWS_ROLE_ARN: arn:aws:iam::203374879162:role/github-actions-aws-cicd-demo

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate release snapshot
        run: |
          echo "Checking release: ${{ inputs.release_sha }}"

          aws s3 ls \
            s3://${{ env.S3_BUCKET }}/_releases/${{ inputs.release_sha }}/

      - name: Remove current deployment
        run: |
          aws s3 rm \
            s3://${{ env.S3_BUCKET }}/ \
            --recursive \
            --exclude "_releases/*"

      - name: Restore selected release
        run: |
          aws s3 sync \
            s3://${{ env.S3_BUCKET }}/_releases/${{ inputs.release_sha }}/ \
            s3://${{ env.S3_BUCKET }}/ \
            --exclude "_releases/*"

      - name: Verify rollback
        run: |
          aws s3 ls s3://${{ env.S3_BUCKET }}/

      - name: Health check
        run: |
          curl --fail --retry 5 --retry-delay 3 \
            http://${{ env.S3_BUCKET }}.s3-website.${{ env.AWS_REGION }}.amazonaws.com/

          echo "Rollback health check passed."

      - name: Rollback completed
        run: |
          echo "Rollback completed successfully."
          echo "Restored release: ${{ inputs.release_sha }}"